#Problem 1

The resulting matrix is a 3x3 matrix. Calculation is done in each box by multiplying each row of the first matrix to each collumn of the second matrix. 
This result in 
[[  6,  29, -20],
[ 12,  52,  38],
[-18, -51, -48]]
matrix

#Problem 2

In [95]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ans = np.matmul(a_ndarray, b_ndarray)
ans

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

#Problem 3

In [97]:
def myMatMul(a, b):
  dimA = a.shape
  dimB = b.shape
  result = []
  if dimA[1] != dimB[0]: print("Cannot be performed")

  for i in range(dimA[0]):
    for j in range(dimB[1]):
      result.append(np.sum(a[i,:] * b[:,j]))

  return np.array(result).reshape(dimA[0], dimB[1])

ans = myMatMul(a_ndarray, b_ndarray)
ans

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

#Problem 4

In [98]:
def myMatMul2(a, b):
  dimA = a.shape
  dimB = b.shape
  result = []
  if dimA[1] != dimB[0]: print("Cannot be performed")
  
  for i in range(dimA[0]):
    for j in range(dimB[1]):
      sum = 0;
      for k in range(dimA[1]):
        sum = sum + a[i, k] * b[k, j]
      result.append(sum)

  return np.array(result).reshape(dimA[0], dimB[1])

ans = myMatMul(a_ndarray, b_ndarray)
ans

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [99]:
#PROBLEM 5

np.transpose(a_ndarray)

array([[-1,  4,  7],
       [ 2, -5,  8],
       [ 3,  6, -9]])